Cortadoverde\Mercadolibre\Entity\Location:
  exclusion_policy: NONE
  properties:
    address_line:
      type: "string"
    city:
      type: "Cortadoverde\\Mercadolibre\\Entity\\Localization"
    country:
      type: "Cortadoverde\\Mercadolibre\\Entity\\Localization"
    latitude:
      type: "float"
    longitude:
      type: "float"
    neighborhood:
      type: "Cortadoverde\\Mercadolibre\\Entity\\Localization"
    open_hours:
      type: "string"
    search_location:
      type: "Cortadoverde\\Mercadolibre\\Entity\\SearchLocation"
    state:
      type: "Cortadoverde\\Mercadolibre\\Entity\\Localization"
    zip_code:
      type: "string"
