Cortadoverde\Mercadolibre\Entity\BuyerReputation:
  exclusion_policy: NONE
  properties:
    canceled_transactions:
      type: "integer"
    tags:
      type: "array"
    transactions:
      type: "Cortadoverde\\Mercadolibre\\Entity\\BuyerTransaction"
